### ISSUE TITLE
This script has a backdoor so be careful when using it, try to locate and remove the backdoor first before making use of it else all your efforts will be in vain

### ISSUE THREAD

**Issue by peterkels** [ChrisBop/eth-nft-drainer#2]

**Comment by Scarletalvey** [comment]
I noticed can you please tell me where the backdoor is and how I fix it

**Comment by peterkels** [comment]
@Scarletalvey  even if i tell you, you won't be able to fix it cause the script that has the backdoor is obfuscated so if you remove the entire code and replace it with a fresh one, it won't work cause there're keywords embeded in it that's meant to trigger the connection to your wallet. to change that simply means you'd have to build the drainer from scratch again.

anyway you can reach me on https://t.me/Kelly_321

i did manage to figure out a way to replace the coder's details on the backdoor to mine

**Comment by peterkels** [comment]
getting drainers for free is impossible, this guy just used this to cashout alot from people that didn't know much. i checked the transaction history on his wallet and he received alot of payments to the point his address has been flagged as phishingwallet.

**Comment by patrapshack** [comment]
did anybody solved the backdoor?

**Comment by Dayplayyyy** [comment]
Can you teach me how to use it

**Comment by patrapshack** [comment]
> Can you teach me how to use it

yep dm me @paradrainers on telegram
